"use client";
import { useMemo, useState } from 'react';
import { Area, ComposedChart, Line, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend, PieChart, Pie, Cell } from 'recharts';
import { buildCashSummary, cashMonth } from '@/lib/cash-summary';
import type { Movement, ProjectedMovement } from '@/lib/types';
const colors=['#3b82f6','#38bdf8','#14b8a6','#818cf8','#f59e0b','#64748b'];
const panel='rounded-xl border bg-card p-3 shadow-sm';
const tooltip={background:'hsl(var(--card))',color:'hsl(var(--foreground))',border:'1px solid hsl(var(--border))',borderRadius:10};
export function CashSummaryPanels({real,planned,currency,forecastUnavailable}:{real:Movement[];planned:ProjectedMovement[];currency:string;forecastUnavailable:boolean}) {
  const [month,setMonth]=useState(()=>cashMonth(new Date()));
  const [lineField,setLineField]=useState<'descPL'|'conceptoPL'|'oficina'>('descPL');
  const data=useMemo(()=>buildCashSummary(real,planned,month,currency,new Date(),lineField),[real,planned,month,currency,lineField]);
  const money=(n:number|null)=>n===null?'Sin proyección':new Intl.NumberFormat('es-BO',{style:'currency',currency,maximumFractionDigits:0}).format(n);
  const pct=(n:number|null)=>n===null?'—':`${n>0?'+':''}${n.toFixed(1)}%`;
  const operating=data.expenses.filter(r=>r.operating), other=data.expenses.filter(r=>!r.operating).reduce((s,r)=>s+r.value,0);
  const total=operating.reduce((s,r)=>s+r.value,0);
  const deltaColor=(delta:number,income:boolean)=>delta===0?'text-muted-foreground':(income?delta>0:delta<0)?'text-emerald-600 dark:text-emerald-400':'text-rose-600 dark:text-rose-400';
  return <section className="space-y-3" aria-label="Análisis mensual del flujo de caja">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">Visión mensual de la operación</h2><p className="mt-1 text-xs text-muted-foreground">Mes independiente del rango superior · Real al día {data.cut} de {data.days} · {currency}</p></div><label className="text-xs text-muted-foreground">Mes de análisis<input aria-label="Mes de análisis" type="month" value={month} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value))setMonth(e.target.value);}} className="ml-3 rounded-lg border bg-card p-2 text-foreground" /></label></div>
    {(!data.hasForecast || forecastUnavailable) && <p className="rounded-lg border bg-muted p-3 text-sm text-muted-foreground">{forecastUnavailable?'No se pudo cargar el flujo proyectado.':'No hay proyección registrada para este mes.'} Las comparaciones se muestran sin datos.</p>}
    {data.missingRates>0 && <p role="status" className="text-sm text-amber-600">{data.missingRates} movimientos sin conversión USD válida quedaron fuera de los importes. USD se estima con la relación saldo USD / saldo BOB del flujo.</p>}
    <div className="grid gap-3 xl:grid-cols-5">
      <div className={`${panel} xl:col-span-3`}><h3 className="text-sm font-semibold">Desempeño diario del mes</h3><p className="mb-2 mt-1 text-xs text-muted-foreground">Ingresos acumulados · Real y flujo proyectado</p><div className="h-[180px]"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data.daily}><defs><linearGradient id="cash-income-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3b82f6" stopOpacity={0.35}/><stop offset="100%" stopColor="#3b82f6" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid vertical={false} stroke="hsl(var(--border))"/><XAxis dataKey="day" tickLine={false} axisLine={false} stroke="#94a3b8" fontSize={11}/><YAxis width={65} tickFormatter={v=>new Intl.NumberFormat('es',{notation:'compact'}).format(v)} tickLine={false} axisLine={false} stroke="#94a3b8" fontSize={11}/><Tooltip contentStyle={tooltip} formatter={(v:number)=>money(v)} labelFormatter={v=>`Día ${v}`}/><Legend/><Area type="monotone" dataKey="actual" name="Real" stroke="#3b82f6" strokeWidth={3} fill="url(#cash-income-fill)" connectNulls={false}/><Line type="monotone" dataKey="forecast" name="Proyectado" stroke="#10b981" strokeWidth={2} dot={false}/></ComposedChart></ResponsiveContainer></div></div>
      <div className={`${panel} xl:col-span-2`}><h3 className="text-sm font-semibold">Ingresos por línea de negocio</h3><label className="mt-2 block text-xs text-muted-foreground">Agrupar por <select aria-label="Agrupar ingresos" value={lineField} onChange={e=>setLineField(e.target.value as typeof lineField)} className="rounded border bg-card p-1"><option value="descPL">Desc P&amp;L</option><option value="conceptoPL">Concepto P&amp;L</option><option value="oficina">Oficina</option></select></label><div className="mt-5 max-h-44 space-y-4 overflow-y-auto">{data.lines.length?data.lines.map(r=><div key={r.name}><div className="mb-1 flex justify-between gap-3 text-xs"><span>{r.name}</span><strong className="shrink-0 tabular-nums">{money(r.value)}</strong></div><div className="h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-blue-500" style={{width:`${Math.max(0,r.value/Math.max(...data.lines.map(r=>r.value))*100)}%`}}/></div></div>):<p className="text-sm text-muted-foreground">Sin ingresos registrados en el mes.</p>}</div></div>
    </div>
    <div className="grid gap-3 xl:grid-cols-3">
      <div className={panel}><h3 className="mb-1 font-semibold">Variaciones principales</h3><p className="mb-2 text-xs text-muted-foreground">Mes seleccionado · Real vs. proyectado hasta el día {data.cut}</p><div className="max-h-56 overflow-auto"><table className="w-full text-xs"><thead><tr className="border-b text-muted-foreground">{['Concepto','Real','Proyectado','Var. %'].map(t=><th key={t} className="p-2 text-left">{t}</th>)}</tr></thead><tbody>{data.variations.map(r=><tr key={r.name+(r.income?'income':'expense')} className="border-b"><td className="py-3">{r.name}</td><td className="p-2 tabular-nums">{money(r.actual)}</td><td className="p-2 tabular-nums">{data.hasForecast?money(r.forecast):'—'}</td><td className={`p-2 ${data.hasForecast?deltaColor(r.delta,r.income):''}`}>{data.hasForecast?pct(r.percent):'—'}</td></tr>)}</tbody></table></div></div>
      <div className={panel}><h3 className="text-sm font-semibold">Composición de gastos operativos</h3>{total>0?<><div className="relative h-40"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={operating} dataKey="value" nameKey="name" innerRadius={48} outerRadius={68} paddingAngle={2} stroke="none">{operating.map((r,i)=><Cell key={r.name} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={tooltip} formatter={(v:number)=>money(v)}/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><strong className="text-sm">{money(total)}</strong><span className="text-xs text-muted-foreground">Operativos</span></div></div><div className="max-h-28 space-y-2 overflow-y-auto">{operating.map((r,i)=><div key={r.name} className="flex items-center gap-2 text-xs"><span className="h-2 w-2 shrink-0 rounded-full" style={{background:colors[i%colors.length]}}/><span className="flex-1">{r.name}</span><span>{(r.value/total*100).toFixed(1)}%</span></div>)}</div></>:<p className="py-8 text-sm text-muted-foreground">Sin gastos operativos identificados.</p>}<details className="mt-4 text-xs text-muted-foreground"><summary className="cursor-pointer">Criterio de clasificación</summary><p className="mt-2">Clasificación provisional por Concepto P&amp;L: nómina, honorarios, alquileres, energía, personal, cargas sociales, infraestructura, comercialización, reclutamiento y viajes. Otros egresos fuera del gráfico: {money(other)}. No equivale a un OPEX contable validado.</p></details></div>
      <div className={panel}><h3 className="text-sm font-semibold">Top 5 de desviaciones del mes</h3><p className="mt-1 text-xs text-muted-foreground">Mayor diferencia absoluta vs. proyectado al corte</p><div className="mt-3 space-y-3">{data.top.length?data.top.map(r=><div key={r.name+(r.income?'income':'expense')} className="flex justify-between gap-3 border-b pb-3 text-sm"><span>{r.name}</span><strong className={`shrink-0 tabular-nums ${deltaColor(r.delta,r.income)}`}>{r.delta>0?'+':''}{money(r.delta)}</strong></div>):<p className="text-sm text-muted-foreground">{data.hasForecast?'Sin desviaciones en el período.':'Sin proyección para comparar.'}</p>}</div></div>
    </div>
    <div className={panel}><h3 className="text-sm font-semibold">Proyección de cierre de mes</h3><p className="mb-2 mt-1 text-xs text-muted-foreground">{data.cut===data.days?'Mes finalizado: importes reales registrados.':'Real al corte + movimientos proyectados posteriores al corte. No incluye pendientes vencidos.'}</p><div className="overflow-auto"><table className="w-full text-sm"><thead className="text-left text-xs text-muted-foreground"><tr>{['Concepto','Real al corte','Cierre estimado','Proyectado del mes','Variación estimada'].map(t=><th className="p-3" key={t}>{t}</th>)}</tr></thead><tbody>{[...data.closing,{name:'Flujo neto',actual:data.income-data.expense,estimate:data.closing.every(r=>r.estimate!==null)?data.closing[0].estimate!-data.closing[1].estimate!:null,forecast:data.hasForecast?data.closing[0].forecast!-data.closing[1].forecast!:null}].map(r=><tr className="border-t" key={r.name}><td className="p-3 font-medium">{r.name}</td><td className="p-3 tabular-nums">{money(r.actual)}</td><td className="p-3 tabular-nums">{money(r.estimate)}</td><td className="p-3 tabular-nums">{money(r.forecast)}</td><td className="p-3 tabular-nums">{r.estimate!==null&&r.forecast!==null?money(r.estimate-r.forecast):'—'}</td></tr>)}</tbody></table></div></div>
  </section>;
}
